import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'hi' | 'mr';

export const translations = {
  en: {
    // Navigation & Common
    app_name: 'Krishi Sakhi',
    subtitle: 'Smart Farm Assistant',
    menu_dashboard: 'Dashboard',
    menu_advisory: 'Smart Advisory',
    menu_disease: 'Disease Check',
    menu_quests: 'Quests',
    menu_leaderboard: 'Leaderboard',
    menu_schemes: 'Govt Schemes',
    menu_profile: 'Profile',
    menu_crops: 'My Crops',
    menu_activities: 'Activities',
    menu_weather: 'Weather',
    menu_community: 'Community',
    menu_connect: 'Farmer Connect',
    menu_mart: 'Animal Mart',
    menu_machinery: 'Machinery Rent/Sell',
    loading: 'Loading...',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    submit: 'Submit',
    close: 'Close',
    search: 'Search...',
    online: 'Online',
    assistant_title: 'Krishi Sakhi Assistant',
    ai_thinking: 'Thinking...',
    chat_placeholder: 'Ask about crops, weather...',
    welcome: 'Welcome',
    welcome_sub: 'Welcome to your smart farming assistant',

    // Dashboard
    quick_actions: 'Quick Actions',
    add_crop: 'Add New Crop',
    add_crop_sub: 'Record a new planting',
    check_weather: 'Check Weather',
    check_weather_sub: 'View forecast',
    ask_community: 'Ask Community',
    ask_community_sub: 'Get expert help',
    disease_check: 'Disease Check',
    disease_check_sub: 'Scan plant health',
    daily_advice: "Today's Farming Advice",
    recent_crops: 'Recent Crops',
    community_activity: 'Community Activity',
    view_all: 'View All',

    // My Crops
    crops_title: 'Farm Production',
    crops_subtitle: 'Track growth, manage cycles, and plan harvests.',
    active_crops: 'Active Crops',
    total_area: 'Total Area',
    acres: 'Acres',
    days: 'Days',
    no_crops: 'No crops added yet',
    start_adding_crops: 'Start by adding the crops you are currently growing.',
    add_first_crop: 'Add your first crop',
    crop_name: 'Crop Name',
    variety: 'Variety',
    sowing_date: 'Sowing Date',
    harvest_date: 'Harvest Date (Est)',
    stage: 'Stage',
    health: 'Health Status',
    irrigation_method: 'Irrigation Method',
    expected_yield: 'Expected Yield',
    seed_source: 'Seed Source',
    next_action: 'Next Action',
    notes: 'Notes',
    image_url: 'Image URL',
    remove_crop: 'Remove',
    update_crop: 'Update Crop',
    save_crop: 'Save Crop',

    // Weather
    weather_title: 'Weather Forecast',
    feels_like: 'Feels like',
    wind: 'Wind',
    humidity: 'Humidity',
    forecast_7_days: '7-Day Forecast',
    today: 'Today',

    // Activities
    activities_title: 'Farm Activities Log',
    activities_subtitle: 'Plan, track, and automate your daily farm tasks.',
    pending_tasks: 'Pending Tasks',
    history: 'History',
    total_logged: 'Total Logged',
    generate_plan: 'Generate Daily Plan',
    ai_planning: 'AI Planning...',
    log_task: 'Log Task',
    task_title: 'Title',
    task_desc: 'Description',
    task_type: 'Type',
    task_date: 'Date',
    save_activity: 'Save Activity',

    // Community
    community_title: 'Farmers Community',
    community_subtitle: 'Ask questions, share advice, and grow together',
    new_post: 'Create Post',
    posted_by: 'Posted by',
    likes: 'Likes',
    replies: 'Replies',
    view_discussion: 'View Discussion',
    search_discussions: 'Search discussions...',
    create_post_title: 'Create New Discussion',
    post_title_placeholder: 'Title of your discussion',
    post_content_placeholder: 'Describe your question or advice in detail...',
    post_tags_placeholder: 'Tags (e.g. Rice, Pest)',
    write_comment: 'Write a helpful comment...',
    post_comment: 'Post Comment',
    no_comments: 'No comments yet. Be the first to reply!',
    back_to_feed: 'Back to Feed',
    trending_tags: 'Trending Tags',
    
    // Smart Community
    discussions: 'Discussions',
    knowledge_base: 'FAQ',
    kb_subtitle: 'Frequently asked questions about farming.',
    verified_answer: 'Verified Answer',
    community_answer: 'Community Answer',
    web_answer: 'Web Answer (External Source)',
    search_web: 'Search from Web',
    searching_web: 'Searching...',
    web_disclaimer: 'This answer is fetched from the internet. It is not expert advice.',
    no_kb_results: 'No matching questions found in FAQ.',
    
    // Connect
    connect_title: 'Global Farmer Connect',
    connect_subtitle: 'Use AI to find farmers with similar profiles around the world.',
    find_peers: 'Find Similar Farmers',
    finding_peers: 'Searching the globe...',
    match_score: 'Match',
    crops: 'Crops',
    connect_btn: 'Connect',
    nearby_matches: 'Nearby Matches',
    global_matches: 'Global Matches',
    profile_missing: 'Profile Missing',
    complete_profile_msg: 'Please complete your profile to enable AI matching with farmers worldwide.',
    complete_profile_btn: 'Complete Profile',
    no_matches: 'No matches found at the moment. Please try again later.',
    not_set: 'Not set',
    edit_profile_tooltip: 'Edit Profile',
    
    // Schemes
    schemes_title: 'Government Schemes',
    schemes_subtitle: 'Discover financial aid, subsidies, and insurance programs.',
    check_eligibility: 'Check Eligibility (AI)',
    close_matchmaker: 'Close Matchmaker',
    ai_matchmaker: 'AI Scheme Matchmaker',
    state: 'State',
    land_area: 'Land Area',
    specific_need: 'Specific Need',
    analyzing_profile: 'Analyzing Profile...',
    find_schemes: 'Find Best Schemes',
    benefits: 'Benefits',
    eligibility: 'Eligibility',
    deadline: 'Deadline',
    match_score_scheme: 'Match',

    // Quests
    quests_title: 'Sustainability Quests',
    quests_subtitle: 'Complete eco-friendly tasks, upload proof for AI verification, and earn rewards!',
    total_points: 'Total Points',
    active_quests_title: 'Active Quests',
    check_in: 'Check In',
    claimed: 'Claimed',
    verify_quest: 'Verify Quest',
    upload_proof: 'Upload Proof',
    verifying: 'Verifying with AI...',
    submit_proof: 'Submit Proof',
    quest_verified: 'Quest Verified!',
    verification_failed: 'Verification Failed',
    try_again: 'Try Again',
    awesome: 'Awesome!',
    tap_to_upload: 'Tap to Take Photo or Upload',

    // Profile
    edit_profile: 'Edit Profile',
    member_since: 'Member since',
    level: 'Level',
    reputation: 'Reputation',
    profile_completion: 'Profile Completion',
    farm_details: 'Farm Details',
    farm_assets: 'Farm Assets',
    contact_personal: 'Contact & Personal',
    compliance: 'Compliance',
    machinery_owned: 'Machinery Owned',
    livestock: 'Livestock',
    primary_crops_history: 'Primary Crops History',
    add_crop_history: 'Add crop (e.g. Cotton)',
    soil_type: 'Soil Type',
    irrigation_sources: 'Irrigation Sources',
    experience: 'Experience',
    years: 'Years',
    language: 'Language',
    organic_certified: 'Organic Certified',
    kcc_holder: 'KCC Holder',
    gender: 'Gender',
    age: 'Age',
    farmer_category: 'Farmer Category',
    district: 'District',
    taluka: 'Taluka / Block',
    village: 'Village',
    pincode: 'PIN Code',
    number_of_plots: 'Number of Plots',
    soil_fertility: 'Soil Fertility',
    soil_test_done: 'Soil Testing Done?',
    last_test_year: 'Last Soil Test Year',
    water_availability: 'Water Availability',
    main_crop: 'Main Crop Type',
    secondary_crop: 'Secondary Crop Type',
    labor_availability: 'Labor Availability',
    modern_techniques: 'Modern Techniques Used?',
    personal_info: 'Personal Information',
    location_details: 'Location Details',
    land_soil_health: 'Land & Soil Health',
    water_irrigation: 'Water & Irrigation',
    crops_practice: 'Crops & Practices',
    resources: 'Resources',

    // Disease Check
    disease_title: 'Plant Disease Detection',
    disease_subtitle: 'Upload a photo of your plant to detect diseases and get treatment advice',
    upload_plant_image: 'Upload Plant Image',
    click_to_upload: 'Click to Upload',
    tips_results: 'Tips for Better Results',
    detect_disease: 'Detect Disease',
    analyzing: 'Analyzing...',
    analysis_report: 'Analysis Report',
    ai_disclaimer: 'AI diagnosis is for informational purposes only. Consult a local agricultural expert.',

    // Advisory
    advisory_title: 'Smart Advisory',
    advisory_subtitle: 'Real-time recommendations based on your soil, crops, and weather.',
    pest_disease_forecast: 'Pest & Disease Forecast',
    risk: 'Risk',
    recommended_action: 'Recommended Action',
    crop_management: 'Crop Management',
    field_conditions: 'Field Conditions (Simulated)',
    soil_moisture: 'Soil Moisture',
    soil_temp: 'Soil Temp',
    soil_ph: 'Soil pH',
    wind_stress: 'Wind Stress',
    ai_generated: 'AI Generated',

    // Animal Mart
    mart_title: 'Farm Animal Marketplace',
    mart_subtitle: 'Buy and sell healthy farm animals directly from other farmers.',
    sell_animal: 'Sell Animal',
    filter_type: 'Filter by Type',
    filter_district: 'Filter by District',
    price_rs: 'Price (₹)',
    contact_seller: 'Contact Seller',
    animal_type: 'Animal Type',
    breed: 'Breed',
    purpose: 'Purpose',
    vaccination_status: 'Vaccinated',
    yes: 'Yes',
    no: 'No',
    health_status: 'Health Status',
    listing_details: 'Listing Details',
    call: 'Call',
    whatsapp: 'WhatsApp',
    posted_on: 'Posted on',

    // Machinery Mart
    machinery_title: 'Farm Machinery Rent & Sell',
    machinery_subtitle: 'Connect with local farmers to rent or buy equipment.',
    list_machine: 'List Machine',
    rent: 'Rent',
    sell: 'Sell',
    machine_type: 'Machine Type',
    brand_model: 'Brand / Model',
    condition: 'Condition',
    year_purchase: 'Year of Purchase',
    per_hour: 'per hour',
    per_day: 'per day',
    verified_owner: 'Verified Owner',
    location_verified: 'Location Verified',
    safety_disclaimer: 'Safety Notice: This platform connects users only. Verify equipment physically before paying.',
    report_listing: 'Report Listing',
    price_unit: 'Price Unit'
  },
  hi: {
    // Navigation & Common
    app_name: 'कृषि सखी',
    subtitle: 'स्मार्ट किसान सहायक',
    menu_dashboard: 'डैशबोर्ड',
    menu_advisory: 'स्मार्ट सलाह',
    menu_disease: 'रोग जांच',
    menu_quests: 'कार्य (Quests)',
    menu_leaderboard: 'लीडरबोर्ड',
    menu_schemes: 'सरकारी योजनाएं',
    menu_profile: 'प्रोफाइल',
    menu_crops: 'मेरी फसलें',
    menu_activities: 'गतिविधियां',
    menu_weather: 'मौसम',
    menu_community: 'समुदाय',
    menu_connect: 'किसान कनेक्ट',
    menu_mart: 'पशु मंडी',
    menu_machinery: 'मशीनरी किराया/बिक्री',
    loading: 'लोड हो रहा है...',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    delete: 'हटाएं',
    edit: 'संपादित करें',
    submit: 'जमा करें',
    close: 'बंद करें',
    search: 'खोजें...',
    online: 'ऑनलाइन',
    assistant_title: 'कृषि सखी सहायक',
    ai_thinking: 'सोच रहा हूँ...',
    chat_placeholder: 'फसल, मौसम के बारे में पूछें...',
    welcome: 'स्वागत है',
    welcome_sub: 'आपके स्मार्ट खेती सहायक में आपका स्वागत है',

    // Dashboard
    quick_actions: 'त्वरित कार्य',
    add_crop: 'नई फसल जोड़ें',
    add_crop_sub: 'नई बुवाई दर्ज करें',
    check_weather: 'मौसम देखें',
    check_weather_sub: 'पूर्वानुमान देखें',
    ask_community: 'समुदाय से पूछें',
    ask_community_sub: 'विशेषज्ञ सहायता प्राप्त करें',
    disease_check: 'रोग जांच',
    disease_check_sub: 'पौधे का स्वास्थ्य स्कैन करें',
    daily_advice: 'आज की खेती सलाह',
    recent_crops: 'हाल ही की फसलें',
    community_activity: 'सामुदायिक गतिविधि',
    view_all: 'सभी देखें',

    // My Crops
    crops_title: 'कृषि उत्पादन',
    crops_subtitle: 'विकास ट्रैक करें, चक्र प्रबंधित करें और कटाई की योजना बनाएं।',
    active_crops: 'सक्रिय फसलें',
    total_area: 'कुल क्षेत्र',
    acres: 'एकड़',
    days: 'दिन',
    no_crops: 'अभी तक कोई फसल नहीं जोड़ी गई',
    start_adding_crops: 'उन फसलों को जोड़कर शुरुआत करें जो आप अभी उगा रहे हैं।',
    add_first_crop: 'अपनी पहली फसल जोड़ें',
    crop_name: 'फसल का नाम',
    variety: 'किस्म',
    sowing_date: 'बुवाई की तारीख',
    harvest_date: 'कटाई की तारीख (अनुमानित)',
    stage: 'चरण',
    health: 'स्वास्थ्य स्थिति',
    irrigation_method: 'सिंचाई विधि',
    expected_yield: 'अपेक्षित उपज',
    seed_source: 'बीज स्रोत',
    next_action: 'अगली कार्रवाई',
    notes: 'नोट्स',
    image_url: 'छवि URL',
    remove_crop: 'हटाएं',
    update_crop: 'फसल अपडेट करें',
    save_crop: 'फसल सहेजें',

    // Weather
    weather_title: 'मौसम पूर्वानुमान',
    feels_like: 'महसूस हो रहा है',
    wind: 'हवा',
    humidity: 'नमी',
    forecast_7_days: '7-दिन का पूर्वानुमान',
    today: 'आज',

    // Activities
    activities_title: 'कृषि गतिविधि लॉग',
    activities_subtitle: 'योजना बनाएं और अपने दैनिक कृषि कार्यों को ट्रैक करें।',
    pending_tasks: 'लंबित कार्य',
    history: 'इतिहास',
    total_logged: 'कुल लॉग',
    generate_plan: 'दैनिक योजना बनाएं',
    ai_planning: 'AI योजना बना रहा है...',
    log_task: 'कार्य लॉग करें',
    task_title: 'शीर्षक',
    task_desc: 'विवरण',
    task_type: 'प्रकार',
    task_date: 'तारीख',
    save_activity: 'गतिविधि सहेजें',

    // Community
    community_title: 'किसान समुदाय',
    community_subtitle: 'प्रश्न पूछें, सलाह साझा करें और साथ बढ़ें',
    new_post: 'पोस्ट बनाएं',
    posted_by: 'द्वारा पोस्ट किया गया',
    likes: 'पसंद',
    replies: 'जवाब',
    view_discussion: 'चर्चा देखें',
    search_discussions: 'चर्चा खोजें...',
    create_post_title: 'नई चर्चा शुरू करें',
    post_title_placeholder: 'आपकी चर्चा का शीर्षक',
    post_content_placeholder: 'अपने प्रश्न या सलाह का विस्तार से वर्णन करें...',
    post_tags_placeholder: 'टैग (जैसे चावल, कीट)',
    write_comment: 'मददगार टिप्पणी लिखें...',
    post_comment: 'टिप्पणी पोस्ट करें',
    no_comments: 'अभी तक कोई टिप्पणी नहीं। उत्तर देने वाले पहले व्यक्ति बनें!',
    back_to_feed: 'फ़ीड पर वापस जाएं',
    trending_tags: 'ट्रेंडिंग टैग',

    // Smart Community
    discussions: 'चर्चा',
    knowledge_base: 'सामान्य प्रश्न (FAQ)',
    kb_subtitle: 'अक्सर पूछे जाने वाले प्रश्न और त्वरित उत्तर।',
    verified_answer: 'सत्यापित उत्तर',
    community_answer: 'सामुदायिक उत्तर',
    web_answer: 'वेब उत्तर (बाहरी स्रोत)',
    search_web: 'वेब से खोजें',
    searching_web: 'खोज रहा है...',
    web_disclaimer: 'यह उत्तर इंटरनेट से लिया गया है। यह विशेषज्ञ सलाह नहीं है।',
    no_kb_results: 'FAQ में कोई प्रश्न नहीं मिला।',

    // Connect
    connect_title: 'ग्लोबल किसान कनेक्ट',
    connect_subtitle: 'दुनिया भर में समान प्रोफाइल वाले किसानों को खोजने के लिए AI का उपयोग करें।',
    find_peers: 'समान किसान खोजें',
    finding_peers: 'दुनिया भर में खोज रहा है...',
    match_score: 'मैच',
    crops: 'फसलें',
    connect_btn: 'कनेक्ट करें',
    nearby_matches: 'पास के किसान',
    global_matches: 'वैश्विक किसान',
    profile_missing: 'प्रोफाइल अधूरा है',
    complete_profile_msg: 'दुनिया भर के किसानों के साथ जुड़ने के लिए कृपया अपना प्रोफाइल पूरा करें।',
    complete_profile_btn: 'प्रोफाइल पूरा करें',
    no_matches: 'फिलहाल कोई मैच नहीं मिला। कृपया बाद में पुनः प्रयास करें।',
    not_set: 'सेट नहीं',
    edit_profile_tooltip: 'प्रोफाइल संपादित करें',

    // Schemes
    schemes_title: 'सरकारी योजनाएं',
    schemes_subtitle: 'वित्तीय सहायता, सब्सिडी और बीमा कार्यक्रमों की खोज करें।',
    check_eligibility: 'पात्रता जांचें (AI)',
    close_matchmaker: 'मैचमेकर बंद करें',
    ai_matchmaker: 'AI योजना मैचमेकर',
    state: 'राज्य',
    land_area: 'भूमि क्षेत्र',
    specific_need: 'विशिष्ट आवश्यकता',
    analyzing_profile: 'प्रोफाइल का विश्लेषण हो रहा है...',
    find_schemes: 'सर्वोत्तम योजनाएं खोजें',
    benefits: 'लाभ',
    eligibility: 'पात्रता',
    deadline: 'अंतिम तिथि',
    match_score_scheme: 'मैच',

    // Quests
    quests_title: 'स्थिरता कार्य (Quests)',
    quests_subtitle: 'पर्यावरण-अनुकूल कार्य पूरे करें, सत्यापन के लिए प्रमाण अपलोड करें और पुरस्कार जीतें!',
    total_points: 'कुल अंक',
    active_quests_title: 'सक्रिय कार्य',
    check_in: 'चेक इन',
    claimed: 'दावा किया गया',
    verify_quest: 'कार्य सत्यापित करें',
    upload_proof: 'प्रमाण अपलोड करें',
    verifying: 'AI के साथ सत्यापित कर रहा है...',
    submit_proof: 'प्रमाण जमा करें',
    quest_verified: 'कार्य सत्यापित!',
    verification_failed: 'सत्यापन विफल',
    try_again: 'पुनः प्रयास करें',
    awesome: 'बहुत बढ़िया!',
    tap_to_upload: 'फोटो लेने या अपलोड करने के लिए टैप करें',

    // Profile
    edit_profile: 'प्रोफाइल संपादित करें',
    member_since: 'सदस्यता',
    level: 'स्तर',
    reputation: 'प्रतिष्ठा',
    profile_completion: 'प्रोफाइल पूर्णता',
    farm_details: 'खेत का विवरण',
    farm_assets: 'खेत की संपत्ति',
    contact_personal: 'संपर्क और व्यक्तिगत',
    compliance: 'अनुपालन',
    machinery_owned: 'मशीनरी',
    livestock: 'पशुधन',
    primary_crops_history: 'मुख्य फसल इतिहास',
    add_crop_history: 'फसल जोड़ें (जैसे कपास)',
    soil_type: 'मिट्टी का प्रकार',
    irrigation_sources: 'सिंचाई के स्रोत',
    experience: 'अनुभव',
    years: 'वर्ष',
    language: 'भाषा',
    organic_certified: 'जैविक प्रमाणित',
    kcc_holder: 'KCC धारक',
    gender: 'लिंग',
    age: 'आयु',
    farmer_category: 'किसान श्रेणी',
    district: 'जिला',
    taluka: 'तालुका / ब्लॉक',
    village: 'गाँव',
    pincode: 'पिन कोड',
    number_of_plots: 'भूखंडों की संख्या',
    soil_fertility: 'मिट्टी की उर्वरता',
    soil_test_done: 'मृदा परीक्षण किया?',
    last_test_year: 'अंतिम परीक्षण वर्ष',
    water_availability: 'पानी की उपलब्धता',
    main_crop: 'मुख्य फसल',
    secondary_crop: 'दूसरी फसल',
    labor_availability: 'श्रमिक उपलब्धता',
    modern_techniques: 'आधुनिक तकनीक?',
    personal_info: 'व्यक्तिगत जानकारी',
    location_details: 'स्थान विवरण',
    land_soil_health: 'भूमि और मिट्टी स्वास्थ्य',
    water_irrigation: 'जल और सिंचाई',
    crops_practice: 'फसलें और प्रथाएं',
    resources: 'संसाधन',

    // Disease Check
    disease_title: 'पौधे का रोग पहचान',
    disease_subtitle: 'रोगों का पता लगाने और उपचार सलाह प्राप्त करने के लिए अपने पौधे की फोटो अपलोड करें',
    upload_plant_image: 'पौधे की छवि अपलोड करें',
    click_to_upload: 'अपलोड करने के लिए क्लिक करें',
    tips_results: 'बेहतर परिणामों के लिए सुझाव',
    detect_disease: 'रोग का पता लगाएं',
    analyzing: 'विश्लेषण कर रहा है...',
    analysis_report: 'विश्लेषण रिपोर्ट',
    ai_disclaimer: 'AI निदान केवल सूचनात्मक उद्देश्यों के लिए है। स्थानीय कृषि विशेषज्ञ से सलाह लें।',

    // Advisory
    advisory_title: 'स्मार्ट सलाह',
    advisory_subtitle: 'आपकी मिट्टी, फसल और मौसम के आधार पर वास्तविक समय की सिफारिशें।',
    pest_disease_forecast: 'कीट और रोग पूर्वानुमान',
    risk: 'जोखिम',
    recommended_action: 'अनुशंसित कार्रवाई',
    crop_management: 'फसल प्रबंधन',
    field_conditions: 'क्षेत्र की स्थिति (सिमुलेटेड)',
    soil_moisture: 'मिट्टी की नमी',
    soil_temp: 'मिट्टी का तापमान',
    soil_ph: 'मिट्टी का पीएच',
    wind_stress: 'हवा का तनाव',
    ai_generated: 'AI जनरेटेड',

    // Animal Mart
    mart_title: 'पशु मंडी',
    mart_subtitle: 'सीधे अन्य किसानों से स्वस्थ पशु खरीदें और बेचें।',
    sell_animal: 'पशु बेचें',
    filter_type: 'प्रकार से फ़िल्टर करें',
    filter_district: 'जिले से फ़िल्टर करें',
    price_rs: 'कीमत (₹)',
    contact_seller: 'विक्रेता से संपर्क करें',
    animal_type: 'पशु का प्रकार',
    breed: 'नस्ल',
    purpose: 'उद्देश',
    vaccination_status: 'टीकाकरण',
    yes: 'हाँ',
    no: 'नहीं',
    health_status: 'स्वास्थ्य स्थिति',
    listing_details: 'विवरण',
    call: 'कॉल',
    whatsapp: 'व्हाट्सएप',
    posted_on: 'पोस्ट किया गया',

    // Machinery Mart
    machinery_title: 'मशीनरी बाजार',
    machinery_subtitle: 'उपकरण किराए पर लेने या खरीदने के लिए स्थानीय किसानों से जुड़ें।',
    list_machine: 'मशीन लिस्ट करें',
    rent: 'किराये पर',
    sell: 'बिक्री के लिए',
    machine_type: 'मशीन का प्रकार',
    brand_model: 'ब्रांड / मॉडल',
    condition: 'स्थिति',
    year_purchase: 'खरीद का वर्ष',
    per_hour: 'प्रति घंटा',
    per_day: 'प्रति दिन',
    verified_owner: 'सत्यापित मालिक',
    location_verified: 'सत्यापित स्थान',
    safety_disclaimer: 'सुरक्षा सूचना: यह मंच केवल उपयोगकर्ताओं को जोड़ता है। भुगतान करने से पहले उपकरण की भौतिक जांच करें।',
    report_listing: 'लिस्टिंग रिपोर्ट करें',
    price_unit: 'कीमत इकाई'
  },
  mr: {
    // Navigation & Common
    app_name: 'कृषी सखी',
    subtitle: 'स्मार्ट शेतकरी सहाय्यक',
    menu_dashboard: 'डॅशबोर्ड',
    menu_advisory: 'कृषी सल्ला',
    menu_disease: 'रोग तपासणी',
    menu_quests: 'उपक्रम (Quests)',
    menu_leaderboard: 'लीडरबोर्ड',
    menu_schemes: 'शासकीय योजना',
    menu_profile: 'प्रोफाइल',
    menu_crops: 'माझी पिके',
    menu_activities: 'कामांची नोंद',
    menu_weather: 'हवामान',
    menu_community: 'समुदाय',
    menu_connect: 'शेतकरी कनेक्ट',
    menu_mart: 'पशु बाजार',
    menu_machinery: 'यंत्रसामग्री भाड्याने/विक्री',
    loading: 'लोड होत आहे...',
    save: 'जतन करा',
    cancel: 'रद्द करा',
    delete: 'काढून टाका',
    edit: 'संपादित करा',
    submit: 'सादर करा',
    close: 'बंद करा',
    search: 'शोधा...',
    online: 'ऑनलाइन',
    assistant_title: 'कृषी सखी सहाय्यक',
    ai_thinking: 'विचार करत आहे...',
    chat_placeholder: 'पीक, हवामानाबद्दल विचारा...',
    welcome: 'स्वागत आहे',
    welcome_sub: 'तुमच्या स्मार्ट शेती सहाय्यकामध्ये स्वागत आहे',

    // Dashboard
    quick_actions: 'जलद क्रिया',
    add_crop: 'नवीन पीक जोडा',
    add_crop_sub: 'नवीन लागवड नोंदवा',
    check_weather: 'हवामान तपासा',
    check_weather_sub: 'अंदाज पहा',
    ask_community: 'समुदायाला विचारा',
    ask_community_sub: 'तज्ञांची मदत मिळवा',
    disease_check: 'रोग तपासणी',
    disease_check_sub: 'पिकांचे आरोग्य तपासा',
    daily_advice: 'आजचा शेती सल्ला',
    recent_crops: 'अलीकडील पिके',
    community_activity: 'सामुदायिक चर्चा',
    view_all: 'सर्व पहा',

    // My Crops
    crops_title: 'शेती उत्पादन',
    crops_subtitle: 'वाढ ट्रॅक करा, नियोजन करा आणि कापणी व्यवस्थापित करा.',
    active_crops: 'सक्रिय पिके',
    total_area: 'एकूण क्षेत्र',
    acres: 'एकर',
    days: 'दिवस',
    no_crops: 'अद्याप कोणतीही पिके जोडलेली नाहीत',
    start_adding_crops: 'तुम्ही सध्या पिकवत असलेली पिके जोडून सुरुवात करा.',
    add_first_crop: 'पहिले पीक जोडा',
    crop_name: 'पिकाचे नाव',
    variety: 'वाण',
    sowing_date: 'पेरणीची तारीख',
    harvest_date: 'कापणीची तारीख (अंदाजे)',
    stage: 'टप्पा',
    health: 'आरोग्य स्थिती',
    irrigation_method: 'सिंचन पद्धत',
    expected_yield: 'अपेक्षित उत्पन्न',
    seed_source: 'बियाणे स्त्रोत',
    next_action: 'पुढील कृती',
    notes: 'टिपा',
    image_url: 'प्रतिमा URL',
    remove_crop: 'काढून टाका',
    update_crop: 'पीक अपडेट करा',
    save_crop: 'पीक जतन करा',

    // Weather
    weather_title: 'हवामान अंदाज',
    feels_like: 'जाणवते',
    wind: 'वारा',
    humidity: 'आर्द्रता',
    forecast_7_days: '७-दिवसांचा अंदाज',
    today: 'आज',

    // Activities
    activities_title: 'शेती कामांची नोंद',
    activities_subtitle: 'नियोजन करा आणि आपल्या दैनंदिन शेती कामांचा मागोवा घ्या.',
    pending_tasks: 'प्रलंबित कामे',
    history: 'इतिहास',
    total_logged: 'एकूण नोंदी',
    generate_plan: 'दैनंदिन योजना तयार करा',
    ai_planning: 'AI योजना बनवत आहे...',
    log_task: 'काम नोंदवा',
    task_title: 'शीर्षक',
    task_desc: 'वर्णन',
    task_type: 'प्रकार',
    task_date: 'तारीख',
    save_activity: 'काम जतन करा',

    // Community
    community_title: 'शेतकरी समुदाय',
    community_subtitle: 'प्रश्न विचारा, सल्ला द्या आणि एकत्र प्रगती करा',
    new_post: 'पोस्ट तयार करा',
    posted_by: 'यांनी पोस्ट केले',
    likes: 'पसंती',
    replies: 'प्रतिक्रिया',
    view_discussion: 'चर्चा पहा',
    search_discussions: 'चर्चा शोधा...',
    create_post_title: 'नवीन चर्चा सुरू करा',
    post_title_placeholder: 'तुमच्या चर्चेचे शीर्षक',
    post_content_placeholder: 'तुमचा प्रश्न किंवा सल्ला सविस्तर सांगा...',
    post_tags_placeholder: 'टॅग (उदा. भात, कीड)',
    write_comment: 'मदतनीस टिप्पणी लिहा...',
    post_comment: 'टिप्पणी पोस्ट करें',
    no_comments: 'अद्याप कोणत्याही टिप्पण्या नाहीत. उत्तर देणारे पहिले व्हा!',
    back_to_feed: 'फीडवर परत जा',
    trending_tags: 'ट्रेंडिंग टॅग',
    
    // Smart Community
    discussions: 'चर्चा',
    knowledge_base: 'सामान्य प्रश्न (FAQ)',
    kb_subtitle: 'सतत विचारले जाणारे प्रश्न आणि त्वरित उत्तरे.',
    verified_answer: 'सत्यापित उत्तर',
    community_answer: 'समुदाय उत्तर',
    web_answer: 'वेब उत्तर (बाह्य स्रोत)',
    search_web: 'वेबवरून शोधा',
    searching_web: 'शोधत आहे...',
    web_disclaimer: 'हे उत्तर इंटरनेटवरून घेतले आहे. हा तज्ञांचा सल्ला नाही.',
    no_kb_results: 'FAQ मध्ये कोणतेही प्रश्न सापडले नाहीत.',

    // Connect
    connect_title: 'ग्लोबल शेतकरी कनेक्ट',
    connect_subtitle: 'जगभरातील समान प्रोफाइल असलेल्या शेतकऱ्यांना शोधण्यासाठी AI वापरा.',
    find_peers: 'समान शेतकरी शोधा',
    finding_peers: 'जगभरात शोधत आहे...',
    match_score: 'मॅच',
    crops: 'पिके',
    connect_btn: 'कनेक्ट करा',
    nearby_matches: 'जवळचे शेतकरी',
    global_matches: 'जागतिक शेतकरी',
    profile_missing: 'प्रोफाइल अपूर्ण आहे',
    complete_profile_msg: 'जगभरातील शेतकऱ्यांशी जुळण्यासाठी कृपया तुमचे प्रोफाइल पूर्ण करा.',
    complete_profile_btn: 'प्रोफाइल पूर्ण करा',
    no_matches: 'सध्या कोणतेही जुळणारे शेतकरी सापडले नाहीत. कृपया नंतर पुन्हा प्रयत्न करा.',
    not_set: 'सेट नाही',
    edit_profile_tooltip: 'प्रोफाइल संपादित करा',

    // Schemes
    schemes_title: 'शासकीय योजना',
    schemes_subtitle: 'आर्थिक मदत, सबसिडी आणि विमा योजना शोधा.',
    check_eligibility: 'पात्रता तपासा (AI)',
    close_matchmaker: 'मॅचमेकर बंद करा',
    ai_matchmaker: 'AI योजना मॅचमेकर',
    state: 'राज्य',
    land_area: 'जमीन क्षेत्र',
    specific_need: 'विशिष्ट गरज',
    analyzing_profile: 'प्रोफाइलचे विश्लेषण होत आहे...',
    find_schemes: 'उत्तम योजना शोधा',
    benefits: 'फायदे',
    eligibility: 'पात्रता',
    deadline: 'अंतिम मुदत',
    match_score_scheme: 'मॅच',

    // Quests
    quests_title: 'शाश्वत उपक्रम (Quests)',
    quests_subtitle: 'पर्यावरणपूरक कामे पूर्ण करा, पुराव्यासाठी फोटो अपलोड करा आणि बक्षिसे मिळवा!',
    total_points: 'एकूण गुण',
    active_quests_title: 'सक्रिय उपक्रम',
    check_in: 'चेक इन',
    claimed: 'मिळाले',
    verify_quest: 'उपक्रम सत्यापित करा',
    upload_proof: 'पुरावा अपलोड करा',
    verifying: 'AI द्वारे तपासणी होत आहे...',
    submit_proof: 'पुरावा सादर करा',
    quest_verified: 'उपक्रम सत्यापित!',
    verification_failed: 'सत्यापन अयशस्वी',
    try_again: 'पुन्हा प्रयत्न करा',
    awesome: 'मस्त!',
    tap_to_upload: 'फोटो काढण्यासाठी किंवा अपलोड करण्यासाठी टॅप करा',

    // Profile
    edit_profile: 'प्रोफाइल संपादित करा',
    member_since: 'सदस्यत्व',
    level: 'स्तर',
    reputation: 'प्रतिष्ठा',
    profile_completion: 'प्रोफाइल पूर्णत्व',
    farm_details: 'शेती तपशील',
    farm_assets: 'शेती मालमत्ता',
    contact_personal: 'संपर्क आणि वैयक्तिक',
    compliance: 'अनुपालन',
    machinery_owned: 'यंत्रसामग्री',
    livestock: 'पशुधन',
    primary_crops_history: 'मुख्य पीक इतिहास',
    add_crop_history: 'पीक जोडा (उदा. कापूस)',
    soil_type: 'मातीचा प्रकार',
    irrigation_sources: 'सिंचन स्रोत',
    experience: 'अनुभव',
    years: 'वर्षे',
    language: 'भाषा',
    organic_certified: 'सेंद्रिय प्रमाणित',
    kcc_holder: 'KCC धारक',
    gender: 'लिंग',
    age: 'वय',
    farmer_category: 'शेतकरी वर्ग',
    district: 'जिल्हा',
    taluka: 'तालुका',
    village: 'गाव',
    pincode: 'पिन कोड',
    number_of_plots: 'भूखंडांची संख्या',
    soil_fertility: 'जमिनीची सुपीकता',
    soil_test_done: 'माती परीक्षण केले का?',
    last_test_year: 'मागील चाचणी वर्ष',
    water_availability: 'पाण्याची उपलब्धता',
    main_crop: 'मुख्य पीक',
    secondary_crop: 'दुय्यम पीक',
    labor_availability: 'मजुरांची उपलब्धता',
    modern_techniques: 'आधुनिक तंत्रज्ञान?',
    personal_info: 'वैयक्तिक माहिती',
    location_details: 'स्थान तपशील',
    land_soil_health: 'जमीन आणि माती आरोग्य',
    water_irrigation: 'पाणी आणि सिंचन',
    crops_practice: 'पिके आणि पद्धती',
    resources: 'संसाधने',

    // Disease Check
    disease_title: 'पीक रोग तपासणी',
    disease_subtitle: 'रोग ओळखण्यासाठी आणि उपचार सल्ला घेण्यासाठी आपल्या पिकाचा फोटो अपलोड करा',
    upload_plant_image: 'पिकाचा फोटो अपलोड करा',
    click_to_upload: 'अपलोड करण्यासाठी क्लिक करा',
    tips_results: 'चांगल्या परिणामांसाठी टिपा',
    detect_disease: 'रोग शोधा',
    analyzing: 'विश्लेषण करत आहे...',
    analysis_report: 'विश्लेषण अहवाल',
    ai_disclaimer: 'AI निदान केवळ माहितीसाठी आहे. स्थानिक कृषी तज्ञाचा सल्ला घ्या.',

    // Advisory
    advisory_title: 'स्मार्ट कृषी सल्ला',
    advisory_subtitle: 'तुमची माती, पीक आणि हवामानावर आधारित रिअल-टाइम शिफारसी.',
    pest_disease_forecast: 'कीड आणि रोग अंदाज',
    risk: 'जोखीम',
    recommended_action: 'शिफारस केलेली कृती',
    crop_management: 'पीक व्यवस्थापन',
    field_conditions: 'शेताची स्थिती (सिमुलेटेड)',
    soil_moisture: 'मातीची ओलावा',
    soil_temp: 'मातीचे तापमान',
    soil_ph: 'मातीचा pH',
    wind_stress: 'वारा ताण',
    ai_generated: 'AI जनरेटेड',

    // Animal Mart
    mart_title: 'पशु बाजार',
    mart_subtitle: 'इतर शेतकऱ्यांकडून थेट निरोगी प्राणी खरेदी आणि विक्री करा.',
    sell_animal: 'पशु विक्री',
    filter_type: 'प्रकारानुसार फिल्टर करा',
    filter_district: 'जिल्ह्यानुसार फिल्टर करा',
    price_rs: 'किंमत (₹)',
    contact_seller: 'विक्रेत्याशी संपर्क साधा',
    animal_type: 'प्राण्याचा प्रकार',
    breed: 'जात',
    purpose: 'उद्देश',
    vaccination_status: 'लसीकरण',
    yes: 'हो',
    no: 'नाही',
    health_status: 'आरोग्य स्थिती',
    listing_details: 'तपशील',
    call: 'कॉल',
    whatsapp: 'व्हॉट्सअ‍ॅप',
    posted_on: 'पोस्ट केले',

    // Machinery Mart
    machinery_title: 'यंत्रसामग्री बाजार',
    machinery_subtitle: 'उपकरणे भाड्याने घेण्यासाठी किंवा खरेदी करण्यासाठी स्थानिक शेतकऱ्यांशी संपर्क साधा.',
    list_machine: 'मशीन जोडा',
    rent: 'भाड्याने',
    sell: 'विक्री',
    machine_type: 'मशीन प्रकार',
    brand_model: 'ब्रँड / मॉडेल',
    condition: 'स्थिती',
    year_purchase: 'खरेदीचे वर्ष',
    per_hour: 'प्रति तास',
    per_day: 'प्रति दिवस',
    verified_owner: 'सत्यापित मालक',
    location_verified: 'सत्यापित स्थान',
    safety_disclaimer: 'सुरक्षा सूचना: हे प्लॅटफॉर्म फक्त वापरकर्त्यांना जोडते. पैसे देण्यापूर्वी उपकरणांची प्रत्यक्ष तपासणी करा.',
    report_listing: 'तक्रार करा',
    price_unit: 'किंमत एकक'
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: typeof translations['en'];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const savedLang = localStorage.getItem('krishi_language') as Language;
    if (savedLang) {
      setLanguageState(savedLang);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('krishi_language', lang);
  };

  const t = translations[language];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
